version: "3.9"

services:
  mysql:
    container_name: "mysql"
    image: "mysql"
    hostname: "mysql"
    restart: always
    privileged: true
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"